#!/usr/bin/env bash

source /opt/ros/melodic/setup.bash

roslaunch test/talker_listener.launch &

echo "Waiting 10 seconds for ROS Master to start..."
sleep 10
clear

/ROS_system_monitor/build/ros_system_monitor